
1
on:
2
  push:
3
    branches:
4
      - master
5
​
6
jobs:
7
​
8
  build_and_push:
9
    name: Build, push, and deploy Docker image to DO Container Registry
10
    runs-on: ubuntu-latest
11
    steps:
12
​
13
    - name: Checkout master
14
      uses: actions/checkout@master
15
​
16
    - name: Build container image latest version
17
      run: docker build -t registry.digitalocean.com/acme/app:latest .
18
​
19
    - name: Install doctl
20
      uses: digitalocean/action-doctl@v2
21
      with:
22
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
23
​
24
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
25
      run: doctl registry login --expiry-seconds 600
26
​
27
    - name: Push image to DigitalOcean Container Registry
28
      run: docker push registry.digitalocean.com/acme/app:latest
29
​
30
  deploy:
31
    runs-on: ubuntu-latest
32
    needs: build_and_push
33
​
34
    steps:
35
      - name: Deploy to Digital Ocean droplet via SSH action
36
        uses: appleboy/ssh-action@v0.1.3
37
        with:
38
          host: ${{ secrets.HOST }}
39
          username: ${{ secrets.USERNAME }}
40
          password: ${{ secrets.PASSWORD }}
41
          port: 22
42
          script: |
43
            cd acme.app
44
            docker-compose stop
45
            docker-compose rm -f
46
            docker-compose pull
47
            docker-compose up -d
